<div class="block block-dashboard-info">
	<div class="block-title"><strong><?php echo __('Profile Picture'); ?></strong></div>
	<div class="block-content">
		<div class="box box-information">
			<strong class="box-title">
				<span><?php echo __('Profile Picture'); ?></span>
			</strong>
			<div class="box-content">
				<img src="<?php echo $this->getProfilePicUrl(); ?>" width="150">
			</div>
		</div>
		<div class="box box-newsletter">
			<strong class="box-title">
				<span><?php echo __('Upload New Profile Picture'); ?></span>
			</strong>
			<div class="box-content">
				<form action="<?php echo $this->getUrl('praveen_profilepic/upload'); ?>" enctype="multipart/form-data" method="POST">
					<input type="file" name="profile_picture" accept="image/*">
					<button type="submit">
						<?php if (strpos($this->getProfilePicUrl(), 'default.jpg') == true) { ?>
							<span><?php echo __('Upload'); ?></span>
						<?php }else{ ?>
							<span><?php echo __('Edit'); ?></span>
						<?php } ?>
					</button>
				</form>
			</div>
		</div>
	</div>
</div>
